#!/usr/bin/php
<?php
   /**
    * Capture the video in a new folder in STORAGEPATH
    */
   try {
    

chdir(__DIR__);
$app_path = realpath(__DIR__."/../");

require_once("$app_path/www/common.php");

$options = $recorder->getSettings();

$folder_name = $recorder->getNewRecordingFolder();

file_put_contents(FILE_CURRENT_PROJECT,$folder_name);

mkdir(STORAGEPATH."/".$folder_name);

$recorder->setProjectMetadata(array("start_time"=>time()));

$audiocmd="";

if ($options["audiosource"]) {
  $audiocmd="-f alsa -itsoffset 6.5 -ac 1 -acodec aac -strict -2 -i ".$options["audiosource"];
}
$cmd="/usr/bin/raspivid -ih -fps ".intval($options["fps"])." -t 0 -w ".intval($options["width"])." -h ".intval($options["height"])." -b ".intval($options["videobitrate"]*1000)." -pf baseline -o - |
/usr/local/bin/ffmpeg $audiocmd -i - -vcodec copy -f segment -segment_list out.list -segment_list_flags +live -segment_list_size 5 -segment_time 4 -segment_time_delta 3 %9d.ts 2>&1 >> /tmp/capture.log";

echo $cmd;
chdir(STORAGEPATH."/".$folder_name);

exec($cmd,$out,$ret);

// This process wait for the kill signal from start-stop-daemon (start_recording / stop_recording)

} catch (Exception $exc) {
    echo $exc->getMessage();
    echo "\n";
    echo $exc->getTraceAsString();
}
