#!/usr/bin/php
<?php
   /**
    * Capture the video in a new folder in STORAGEPATH
    */

chdir("/var/www/sh");
require_once("../www/common.php");

$options=getSettings();
/*
$default_video_settings=array(
	"width" => "1280",
	"height" => "720",
	"fps" => "25", // number of images per second
	"videobitrate" => "8000", // in kbps
	"audiosource" => "hw:1", // alsa audio source ("" for no audio)
	"audiobitrate" => "128", // in kbps
);
*/

$folder=getNewRecordingFolder();


file_put_contents(RECORDING_FOLDER,$folder);
mkdir(STORAGEPATH."/".$folder);
setProjectMetadata(array("start_time"=>time()));
$audiocmd="";
if ($options["audiosource"]) {
  $audiocmd="-f alsa -itsoffset 6.5 -ac 1 -i ".$options["audiosource"]." -acodec aac -strict -2";
}

$cmd="/usr/bin/raspivid -ih -fps ".intval($options["fps"])." -t 0 -w ".intval($options["width"])." -h ".intval($options["height"])." -b ".intval($options["videobitrate"]*1000)." -pf baseline -o - |
/usr/local/bin/ffmpeg $audiocmd -i - -vcodec copy -f segment -segment_list out.list -segment_list_flags +live -segment_list_size 5 -segment_time 4 -segment_time_delta 3 %9d.ts";

chdir(STORAGEPATH."/".$folder);

exec($cmd,$out,$ret);

// This process wait for the kill signal from start-stop-daemon (start_recording / stop_recording)

