#!/usr/bin/php
<?php

chdir(__DIR__);
$app_path = realpath(__DIR__."/../");

require_once("$app_path/www/common.php");

$cmd="start-stop-daemon --start --pidfile ".escapeshellarg(RASPIVID_PID)
  ." --background --make-pidfile --exec "
  ."$app_path/sh/capture_daemon 2>&1";
  
  passthru($cmd,$ret);
  echo $cmd;
  exit($ret);

