#!/usr/bin/php
<?php

chdir(__DIR__);
$sh_path = __DIR__;
require_once("../www/common.php");

$cmd="start-stop-daemon --start --pidfile ".escapeshellarg(RASPIVID_PID)
  ." --background --make-pidfile --exec "
  ."${sh_path}/capture_daemon 2>&1";
  
  passthru($cmd,$ret);
  exit($ret);

