#!/usr/bin/php
<?php

require_once("../www/common.php");

$cmd="killall raspivid";
passthru($cmd,$ret);

sleep(1);

$cmd="start-stop-daemon --oknodo --stop --pidfile ".escapeshellarg(RASPIVID_PID);
passthru($cmd,$ret);

setProjectMetadata(array("end_time"=>time()));
// CLEANUP
@unlink(CAPTURE_FILE);
@unlink(RECORDING_FOLDER);

exit($ret);



