#!/usr/bin/php
<?php

$app_path = realpath(__DIR__."/../");
require_once($app_path."/www/common.php");

$cmd="killall raspivid";
passthru($cmd,$ret);

sleep(1);

$cmd="start-stop-daemon --oknodo --stop --pidfile ".escapeshellarg(RASPIVID_PID);
passthru($cmd,$ret);

setProjectMetadata(array("end_time"=>time()));
// CLEANUP
@unlink(CAPTURE_FILE);
@unlink(FILE_CURRRENT_RECORDING_FOLDER);

exit($ret);



